### ISSUE TITLE
stream: showNoise fails with TypeError: argument is not an mpz

### ISSUE THREAD

**Issue by renapagli** [DiODeProject/MuMoT#219]
Stream plot with showNoise=True

`stream3 = model3.stream('S','I', showFixedPoints = False, showNoise = True)`

fails in Epidemic Models Demo notebook stream 3 (§1.3) (see stack trace error below). 

The error is not fully reproducible as sometimes there will be no error raised and the plot will be generated incorrectly (the plot will show no noise oval shaded area in this case).

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-33-3d2753b5751c> in <module>()
----> 1 stream3 = model3.stream('S','I', showFixedPoints = False, showNoise = True)

~\Anaconda3\envs\mumot-env2\lib\site-packages\mumot\__init__.py in stream(self, stateVariable1, stateVariable2, stateVariable3, params, initWidgets, **kwargs)
   1016 
   1017             # construct view
-> 1018             modelView = MuMoTstreamView(self, viewController, SOL_2ndOrdMomDict, stateVariable1, stateVariable2, stateVariable3, params=params, **kwargs)
   1019 
   1020             viewController.setView(modelView)

~\Anaconda3\envs\mumot-env2\lib\site-packages\mumot\__init__.py in __init__(self, model, controller, SOL_2ndOrd, stateVariable1, stateVariable2, stateVariable3, figure, params, **kwargs)
   4705             self._checkConstReactants = None
   4706         silent = kwargs.get('silent', False)
-> 4707         super().__init__(model, controller, SOL_2ndOrd, stateVariable1, stateVariable2, stateVariable3, figure, params, **kwargs)
   4708         self._generatingCommand = "stream"
   4709 

~\Anaconda3\envs\mumot-env2\lib\site-packages\mumot\__init__.py in __init__(self, model, controller, SOL_2ndOrd, stateVariable1, stateVariable2, stateVariable3, figure, params, **kwargs)
   4170 
   4171         if not(silent):
-> 4172             self._plot_field()
   4173 
   4174 

~\Anaconda3\envs\mumot-env2\lib\site-packages\mumot\__init__.py in _plot_field(self, _)
   4721 
   4722 
-> 4723         super()._plot_field()
   4724 
   4725         if self._stateVariable3 is None:

~\Anaconda3\envs\mumot-env2\lib\site-packages\mumot\__init__.py in _plot_field(self)
   4404                             #initState[reactant] = 1 - sum(initState.values())
   4405                             iniSum = 0
-> 4406                             for val in initState.values(): iniSum += np.real(val)
   4407                             initState[reactant] = 1 - iniSum
   4408                     #print(initState)

~\Anaconda3\envs\mumot-env2\lib\site-packages\sympy\core\decorators.py in __sympifyit_wrapper(a, b)
     89                 if not hasattr(b, '_op_priority'):
     90                     b = sympify(b, strict=True)
---> 91                 return func(a, b)
     92             except SympifyError:
     93                 return retval

~\Anaconda3\envs\mumot-env2\lib\site-packages\sympy\core\numbers.py in __add__(self, other)
   1153         if isinstance(other, Number) and global_evaluate[0]:
   1154             rhs, prec = other._as_mpf_op(self._prec)
-> 1155             return Float._new(mlib.mpf_add(self._mpf_, rhs, prec, rnd), prec)
   1156         return Number.__add__(self, other)
   1157 

~\Anaconda3\envs\mumot-env2\lib\site-packages\mpmath\libmp\libmpf.py in mpf_add(s, t, prec, rnd, _sub)
    766         return t
    767     if sman:
--> 768         return normalize1(ssign, sman, sexp, sbc, prec or sbc, rnd)
    769     return s
    770 

TypeError: argument is not an mpz
```

**Comment by tbose1** [comment]
I could not reproduce this error. However, I found another (unrelated) error which I fixed via 7646053dd1dfff88768128d57228cbfda2a798c7. 

The Epidemic Models Demo notebook runs now error-free on my system. 

@renapagli could you please pull the most recent version of MuMoT and re-run your notebook to see if you still observe this error. As a note, noise in this case is computed using `SSA()`. You need to look carefully to spot a thin green vertical line in your stream3 plot in §1.3 (i.e. almost no noise in the population of susceptible individuals and a small amount of noise in the population of infected individuals). This seems to somewhat agree with the subsequent ssa-figure (set Simulation time=2 and Number of runs =20 on the sliders, these are the parameters to compute noise via SSA in the stream plot). So, it probably works as it should although the noise ellipse is rather a line than a 2d shape in this case. What do you think?  Please leave a comment below to see if there is still something that needs to be done or if we can close this issue. Thanks.

**Comment by renapagli** [comment]
@tbose1 , thanks for looking into this. The `argument is not an mpz` error is still happening on my end. I was unable to get the plot working so I could not check to see if it is working correctly. Any ideas on what else I could try on my end to better diagnose the issue?

**Comment by tbose1** [comment]
Thanks @renapagli, just to double-check did you initially install MuMoT in your environment as it's described in the [installation instructions](https://diodeproject.github.io/MuMoT/install.html)? After you pulled the latest version did you re-install MuMoT using `python -m pip install --upgrade --no-deps path/to/clone/of/MuMoT/repository` within your environment. If you haven't already done this could you please give it a try (also restart the running IPython kernel in your notebook).

**Comment by renapagli** [comment]
@tbose1 I'm sorry it took me so long to get back to you. I had problems with my setup. I couldn't update conda and had to reinstall. I then tried to install mumot but the installation kept failing because of scipy.  Might be related to [this](https://stackoverflow.com/questions/26575587/cant-install-scipy-through-pip). I then installed scipy, pydstools, and sympy manually through conda to make mumot work in my windows machine. I think the installation problems might have to do with the new version of conda which uses Anaconda Navigator. Have you seen any similar problems with MacOS? 

Anyways, long story short, I cannot reproduce the mpz error anymore. So we could close that part of the issue. However, I cannot see the thin green line you mention. Even if it is there, I wouldn't consider it to be the right behavior. Is there a way to change the settings of `noise=True` in `stream` to Simulation time=100 and number of runs =10? That would work a lot better.

**Comment by jarmarshall** [comment]
@renapagli we currently have plans to set number of runs (issue #256) but not for simulation time - that could also be useful I suppose
@tbose1 are you able to upload a grab of the plot?
Seems we may need to close this and replace with a new issue relating to noise calculation for this example, maybe for the second release milestone.

**Comment by tbose1** [comment]
@renapagli thanks for doing the test. As @jarmarshall mentioned there are some plans to allow a bit more flexibility for the noise computations. However, when I tried the new parameter combination you suggested (Simulation time=100 and number of runs =10) in stream3 this made the noise completely vanish, probably because there is less variation towards the end of the simulation (t=100) compared with the initial phase of the simulation (t=2). To see this run the last cell in §1.3 in the Epidemics Model demo notebook (ssa = model3.SSA(...)) - the curves are constant horizontal lines for t>=45. I hope you observe something similar in your study of the model. 

I have attached the graph with the thin green line (see \Phi_S=0 and 0.45 < \Phi_I < 0.5). There doesn't seem to be any variation in \Phi_S direction, perhaps there are some problems because it's so close to zero and negative populations are not allowed in MuMoT.

If you have more comments please let me know, otherwise I will follow @jarmarshall's advice and close this issue and open a new one related to noise computation for the second release milestones. 

![epidemicsgraph_shownoise_select](https://user-images.githubusercontent.com/16595372/53334802-bb2be280-38f1-11e9-9858-2e9a17843f77.png)

![epidemicsgraph_shownoise](https://user-images.githubusercontent.com/16595372/53334673-61c3b380-38f1-11e9-8ce5-647b7c619c51.png)

**Comment by renapagli** [comment]
@tbose1 thanks for the figures. Now it is clear. We can close this issue and start a new one.

**Comment by tbose1** [comment]
After face to face discussion with @jarmarshall and @joefresna today I'm closing this, as the behaviour of the noise calculations seems to make sense. Noise is calculated via stochastic simulation algorithm starting from a stable stationary state. In line with my comments above it is possible that this leads to small-to-almost-zero variations in the S population.

**Comment by joefresna** [comment]
@renapagli , the pull request #286 also adds the requested functionality (i.e. the possibility to specify the number of runs, the time, and the type of visualization as red dots or green ellipse)
